name = "Skyforge"
author = "Athezu"
version = "0.8.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "202ac5d83d1275ebfe132e6a1dd798904a23083fe7985612d01a67121aa5a09d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
