name = "Skyforge"
author = "Athezu"
version = "0.9.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afee1959c4f960d2688789480be1f8bb28f9a9f61dfdf38436627b3f2da3aff8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
